# Generated by Django 4.0.5 on 2022-07-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeEntity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number_side', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
