# Generated by Django 4.0.5 on 2022-07-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0002_alter_shapeentity_number_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapeentity',
            name='depth',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shapeentity',
            name='height',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shapeentity',
            name='width',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
