# Generated by Django 4.0.5 on 2022-07-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0003_shapeentity_depth_shapeentity_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapeentity',
            name='number_side',
        ),
    ]
