# Generated by Django 4.0.5 on 2022-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0004_remove_shapeentity_number_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapeentity',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
